# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/colorbar.xdc

# IP: ip/pll_108/pll_108.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pll_108 || ORIG_REF_NAME==pll_108} -quiet] -quiet
