# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/project/VGA/vga_rom/vivado/project_1.srcs/sources_1/ip/rom_vga/rom_vga.xci
# IP: The module: 'rom_vga' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/project/VGA/vga_rom/vivado/project_1.srcs/sources_1/ip/rom_vga/rom_vga_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_vga'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/project/VGA/vga_rom/vivado/project_1.srcs/sources_1/ip/rom_vga/rom_vga.xci
# IP: The module: 'rom_vga' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/project/VGA/vga_rom/vivado/project_1.srcs/sources_1/ip/rom_vga/rom_vga_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
