######################################################################
#
# File name : tb_counter.udo
# Created on: Wed Sep 06 12:30:58 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
