######################################################################
#
# File name : tb_counter_wave.do
# Created on: Wed Sep 06 12:30:58 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
