######################################################################
#
# File name : tb_counter_compile.do
# Created on: Wed Sep 06 12:30:56 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../../rtl/counter.v" \
"../../../../../sim/tb_counter.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

