######################################################################
#
# File name : tb_simple_fsm_wave.do
# Created on: Thu Sep 07 17:03:14 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
