######################################################################
#
# File name : harf_adder_wave.do
# Created on: Sun Sep 03 21:32:14 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
