######################################################################
#
# File name : harf_adder_compile.do
# Created on: Sun Sep 03 21:32:13 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../../rtl/harf_adder.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

