######################################################################
#
# File name : tb_harf_adder_simulate.do
# Created on: Sun Sep 03 21:36:59 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_harf_adder xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_harf_adder_wave.do}

view wave
view structure
view signals

do {tb_harf_adder.udo}

run 1000ns
