######################################################################
#
# File name : tb_flip_flop_wave.do
# Created on: Tue Sep 05 21:00:16 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
