######################################################################
#
# File name : tb_flip_flop_compile.do
# Created on: Tue Sep 05 21:00:15 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../../rtl/flip_flop.v" \
"../../../../../rtl/flip_flop_1.v" \
"../../../../../sim/tb_flip_flop.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

