######################################################################
#
# File name : tb_decoder3_8_wave.do
# Created on: Sun Sep 03 17:42:58 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
