######################################################################
#
# File name : tb_decoder3_8_simulate.do
# Created on: Sun Sep 03 17:42:58 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_decoder3_8 xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_decoder3_8_wave.do}

view wave
view structure
view signals

do {tb_decoder3_8.udo}

run 1000ns
