# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/project/IP/IP_FIFO/SCFIFO/SCFIFO.srcs/sources_1/ip/scfifo_256x8/scfifo_256x8.xci
# IP: The module: 'scfifo_256x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/project/IP/IP_FIFO/SCFIFO/SCFIFO.srcs/sources_1/ip/scfifo_256x8/scfifo_256x8.xdc
# XDC: The top module name and the constraint reference have the same name: 'scfifo_256x8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/project/IP/IP_FIFO/SCFIFO/SCFIFO.srcs/sources_1/ip/scfifo_256x8/scfifo_256x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scfifo_256x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/project/IP/IP_FIFO/SCFIFO/SCFIFO.srcs/sources_1/ip/scfifo_256x8/scfifo_256x8.xci
# IP: The module: 'scfifo_256x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/project/IP/IP_FIFO/SCFIFO/SCFIFO.srcs/sources_1/ip/scfifo_256x8/scfifo_256x8.xdc
# XDC: The top module name and the constraint reference have the same name: 'scfifo_256x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/project/IP/IP_FIFO/SCFIFO/SCFIFO.srcs/sources_1/ip/scfifo_256x8/scfifo_256x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scfifo_256x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
