# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/project/IP/IP_RAM/RAM/RAM.srcs/sources_1/ip/ram_256x8/ram_256x8.xci
# IP: The module: 'ram_256x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/project/IP/IP_RAM/RAM/RAM.srcs/sources_1/ip/ram_256x8/ram_256x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_256x8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/project/IP/IP_RAM/RAM/RAM.srcs/sources_1/ip/ram_256x8/ram_256x8.xci
# IP: The module: 'ram_256x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/project/IP/IP_RAM/RAM/RAM.srcs/sources_1/ip/ram_256x8/ram_256x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_256x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
