######################################################################
#
# File name : tb_simplex_fsm_compile.do
# Created on: Fri Sep 08 17:08:16 +0800 2023
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"tb_simplex_fsm_func_synth.v" \
"../../../../../../../sim/tb_simplex_fsm.v" \


quit -force

