######################################################################
#
# File name : tb_simplex_fsm_wave.do
# Created on: Fri Sep 08 17:08:17 +0800 2023
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
