######################################################################
#
# File name : tb_simplex_fsm_compile.do
# Created on: Mon Sep 11 20:33:15 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../../../rtl/simplex_fsm.v" \
"../../../../../../sim/tb_simplex_fsm.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

