######################################################################
#
# File name : tb_simplex_fsm_wave.do
# Created on: Fri Sep 08 16:57:30 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
