######################################################################
#
# File name : tb_led_wave.do
# Created on: Fri Sep 01 16:12:11 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
