######################################################################
#
# File name : tb_full_adder.udo
# Created on: Mon Sep 04 19:55:31 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
