######################################################################
#
# File name : tb_full_adder_wave.do
# Created on: Mon Sep 04 19:55:31 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
