######################################################################
#
# File name : tb_water_led_wave.do
# Created on: Wed Sep 06 15:11:06 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
