######################################################################
#
# File name : tb_water_led_compile.do
# Created on: Wed Sep 06 15:11:05 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../../rtl/water_led.v" \
"../../../../../rtl/tb_water_led.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

