######################################################################
#
# File name : tb_water_led_simulate.do
# Created on: Wed Sep 06 15:11:06 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_water_led xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_water_led_wave.do}

view wave
view structure
view signals

do {tb_water_led.udo}

run 1000ns
