######################################################################
#
# File name : tb_Mux2_1_wave.do
# Created on: Fri Sep 01 19:26:20 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
