######################################################################
#
# File name : tb_Mux2_1_compile.do
# Created on: Fri Sep 01 19:56:14 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../../rtl/Mux2_1.v" \
"../../../../../rtl/tb_Mux2_1.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

