######################################################################
#
# File name : tb_Mux2_1_simulate.do
# Created on: Fri Sep 01 19:56:16 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_Mux2_1 xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_Mux2_1_wave.do}

view wave
view structure
view signals

do {tb_Mux2_1.udo}

run 1000ns
