# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/project/VGA/vga_char/char.srcs/sources_1/ip/pll_108/pll_108.xci
# IP: The module: 'pll_108' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/project/VGA/vga_char/char.srcs/sources_1/ip/pll_108/pll_108_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_108'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/project/VGA/vga_char/char.srcs/sources_1/ip/pll_108/pll_108.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_108'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/project/VGA/vga_char/char.srcs/sources_1/ip/pll_108/pll_108_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_108'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/project/VGA/vga_char/char.srcs/sources_1/ip/pll_108/pll_108.xci
# IP: The module: 'pll_108' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/project/VGA/vga_char/char.srcs/sources_1/ip/pll_108/pll_108_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_108'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/project/VGA/vga_char/char.srcs/sources_1/ip/pll_108/pll_108.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_108'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/project/VGA/vga_char/char.srcs/sources_1/ip/pll_108/pll_108_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_108'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
