######################################################################
#
# File name : tb_full_adder_compile.do
# Created on: Mon Sep 04 19:18:33 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../project_1.srcs/sources_1/imports/rtl/full_adder.v" \
"../../../../project_1.srcs/sources_1/imports/rtl/harf_adder.v" \
"../../../../project_1.srcs/sources_1/imports/rtl/tb_full_adder.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

